"""add synthesis_configs table

Revision ID: 2fc126fd07b2
Revises: 54548631fcaa
Create Date: 2025-11-03 14:14:53.875548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc126fd07b2'
down_revision: Union[str, None] = '54548631fcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthesis_configs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('anima_id', sa.Uuid(), nullable=False),
    sa.Column('time_weight', sa.Float(), nullable=False),
    sa.Column('event_weight', sa.Float(), nullable=False),
    sa.Column('token_weight', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('job_interval_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['anima_id'], ['animas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthesis_configs_anima_id'), 'synthesis_configs', ['anima_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synthesis_configs_anima_id'), table_name='synthesis_configs')
    op.drop_table('synthesis_configs')
    # ### end Alembic commands ###
