"""add knowledge and knowledge_audit_log tables

Revision ID: 7bd636c06650
Revises: 1e85ffe7ac8a
Create Date: 2025-11-11 09:10:56.401902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bd636c06650'
down_revision: Union[str, None] = '1e85ffe7ac8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('anima_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_type', sa.Enum('FACT', 'CONCEPT', 'METHOD', 'PRINCIPLE', 'EXPERIENCE', name='knowledgetype'), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('INTERNAL', 'EXTERNAL', name='sourcetype'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
    sa.ForeignKeyConstraint(['anima_id'], ['animas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_anima_id'), 'knowledge', ['anima_id'], unique=False)
    op.create_index(op.f('ix_knowledge_is_deleted'), 'knowledge', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_knowledge_type'), 'knowledge', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_knowledge_topic'), 'knowledge', ['topic'], unique=False)
    op.create_table('knowledge_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'RESTORE', name='auditaction'), nullable=False),
    sa.Column('source_type', sa.Enum('INTERNAL', 'EXTERNAL', name='sourcetype'), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_audit_log_action'), 'knowledge_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_knowledge_audit_log_created_at'), 'knowledge_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_audit_log_knowledge_id'), 'knowledge_audit_log', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_audit_log_source_id'), 'knowledge_audit_log', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_audit_log_source_id'), table_name='knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_audit_log_knowledge_id'), table_name='knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_audit_log_created_at'), table_name='knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_audit_log_action'), table_name='knowledge_audit_log')
    op.drop_table('knowledge_audit_log')
    op.drop_index(op.f('ix_knowledge_topic'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_knowledge_type'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_is_deleted'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_anima_id'), table_name='knowledge')
    op.drop_table('knowledge')
    # ### end Alembic commands ###
