"""add last_synthesis_check_at to synthesis_configs

Revision ID: 8308bce5db8b
Revises: c40110b2c4f1
Create Date: 2025-11-07 15:13:46.675620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8308bce5db8b'
down_revision: Union[str, None] = 'c40110b2c4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add last_synthesis_check_at column to track threshold check timestamp
    op.add_column('synthesis_configs', sa.Column('last_synthesis_check_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synthesis_configs', 'last_synthesis_check_at')
    # ### end Alembic commands ###
