"""add rls performance indexes

Revision ID: 9d0eaf1d64c1
Revises: bf3756b1b88e
Create Date: 2025-11-08 17:52:15.345866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d0eaf1d64c1'
down_revision: Union[str, None] = 'bf3756b1b88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create index on animas.user_id for RLS policy performance
    op.create_index(op.f('ix_animas_user_id'), 'animas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index on animas.user_id
    op.drop_index(op.f('ix_animas_user_id'), table_name='animas')
    # ### end Alembic commands ###
