"""add user_id foreign key to animas table

Revision ID: bf3756b1b88e
Revises: 8308bce5db8b
Create Date: 2025-11-08 14:07:33.790523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf3756b1b88e'
down_revision: Union[str, None] = '8308bce5db8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id foreign key to animas table
    op.add_column('animas', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_animas_user_id', 'animas', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove user_id foreign key from animas table
    op.drop_constraint('fk_animas_user_id', 'animas', type_='foreignkey')
    op.drop_column('animas', 'user_id')
    # ### end Alembic commands ###
