"""add memories_events junction table with CASCADE and CHECK constraint

Revision ID: cec26bf17d4d
Revises: ea8543bfd9f8
Create Date: 2025-10-20 22:24:44.359724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec26bf17d4d'
down_revision: Union[str, None] = 'ea8543bfd9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories_events',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('link_strength', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('link_strength >= 0.0 AND link_strength <= 1.0', name='ck_link_strength_range'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'event_id', name='uq_memories_events_memory_event')
    )
    op.create_index(op.f('ix_memories_events_event_id'), 'memories_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_memories_events_link_strength'), 'memories_events', ['link_strength'], unique=False)
    op.create_index(op.f('ix_memories_events_memory_id'), 'memories_events', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_events_memory_id'), table_name='memories_events')
    op.drop_index(op.f('ix_memories_events_link_strength'), table_name='memories_events')
    op.drop_index(op.f('ix_memories_events_event_id'), table_name='memories_events')
    op.drop_table('memories_events')
    # ### end Alembic commands ###
