"""add identity tables and standardize uuid generation

Revision ID: dc050041bb02
Revises: d741667e529a
Create Date: 2025-11-28 22:53:15.704821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc050041bb02'
down_revision: Union[str, None] = 'd741667e529a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create identities table
    op.create_table('identities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('anima_id', sa.Uuid(), nullable=False),
    sa.Column('personality_type', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='personalitytype'), nullable=True),
    sa.Column('energy_spectrum', sa.Float(), nullable=True),
    sa.Column('information_spectrum', sa.Float(), nullable=True),
    sa.Column('decision_spectrum', sa.Float(), nullable=True),
    sa.Column('lifestyle_spectrum', sa.Float(), nullable=True),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.Text(), nullable=True),
    sa.Column('decision_patterns', sa.Text(), nullable=True),
    sa.Column('interaction_preferences', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_identity_confidence_range'),
    sa.CheckConstraint('decision_spectrum >= 0.0 AND decision_spectrum <= 1.0', name='ck_identity_decision_spectrum_range'),
    sa.CheckConstraint('energy_spectrum >= 0.0 AND energy_spectrum <= 1.0', name='ck_identity_energy_spectrum_range'),
    sa.CheckConstraint('information_spectrum >= 0.0 AND information_spectrum <= 1.0', name='ck_identity_information_spectrum_range'),
    sa.CheckConstraint('lifestyle_spectrum >= 0.0 AND lifestyle_spectrum <= 1.0', name='ck_identity_lifestyle_spectrum_range'),
    sa.ForeignKeyConstraint(['anima_id'], ['animas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_anima_id'), 'identities', ['anima_id'], unique=True)
    op.create_index(op.f('ix_identities_personality_type'), 'identities', ['personality_type'], unique=False)

    # Create identity_audit_log table
    op.create_table('identity_audit_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'ASSESS', 'EVOLVE', name='identityauditaction'), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=True),
    sa.Column('source_memory_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_audit_log_action'), 'identity_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_identity_audit_log_created_at'), 'identity_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_identity_audit_log_identity_id'), 'identity_audit_log', ['identity_id'], unique=False)
    op.create_index(op.f('ix_identity_audit_log_source_memory_id'), 'identity_audit_log', ['source_memory_id'], unique=False)

    # Standardize UUID generation: add server_default to existing tables
    # (existing rows already have UUIDs, this just ensures new inserts use server-side generation)
    op.alter_column('knowledge', 'id',
        server_default=sa.text('gen_random_uuid()'))
    op.alter_column('knowledge_audit_log', 'id',
        server_default=sa.text('gen_random_uuid()'))
    op.alter_column('knowledge_audit_log', 'created_at',
        server_default=sa.text('now()'))

    # Note: checkpoint_* tables are managed by LangGraph, not alembic - do not drop
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove server_defaults from knowledge tables
    op.alter_column('knowledge_audit_log', 'created_at', server_default=None)
    op.alter_column('knowledge_audit_log', 'id', server_default=None)
    op.alter_column('knowledge', 'id', server_default=None)

    # Drop identity_audit_log table
    op.drop_index(op.f('ix_identity_audit_log_source_memory_id'), table_name='identity_audit_log')
    op.drop_index(op.f('ix_identity_audit_log_identity_id'), table_name='identity_audit_log')
    op.drop_index(op.f('ix_identity_audit_log_created_at'), table_name='identity_audit_log')
    op.drop_index(op.f('ix_identity_audit_log_action'), table_name='identity_audit_log')
    op.drop_table('identity_audit_log')

    # Drop identities table (and enum)
    op.drop_index(op.f('ix_identities_personality_type'), table_name='identities')
    op.drop_index(op.f('ix_identities_anima_id'), table_name='identities')
    op.drop_table('identities')

    # Drop enums
    sa.Enum(name='identityauditaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='personalitytype').drop(op.get_bind(), checkfirst=True)

    # Note: checkpoint_* tables are managed by LangGraph, not alembic
    # ### end Alembic commands ###
