"""add memories table

Revision ID: ea8543bfd9f8
Revises: 6d97e4d18837
Create Date: 2025-10-18 22:19:06.513335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8543bfd9f8'
down_revision: Union[str, None] = '6d97e4d18837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('spirit_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'DECAYING', 'ARCHIVED', name='memorystate'), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('decay_score', sa.Float(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['spirit_id'], ['spirits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_importance'), 'memories', ['importance'], unique=False)
    op.create_index(op.f('ix_memories_spirit_id'), 'memories', ['spirit_id'], unique=False)
    op.create_index(op.f('ix_memories_state'), 'memories', ['state'], unique=False)
    op.create_index(op.f('ix_memories_time_end'), 'memories', ['time_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_time_end'), table_name='memories')
    op.drop_index(op.f('ix_memories_state'), table_name='memories')
    op.drop_index(op.f('ix_memories_spirit_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_importance'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
