"""add role and author fields to events

Revision ID: f699f48a6e39
Revises: d1575f589a89
Create Date: 2025-10-27 07:22:12.369043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f699f48a6e39'
down_revision: Union[str, None] = 'd1575f589a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('author', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_role'), 'events', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_role'), table_name='events')
    op.drop_column('events', 'author')
    op.drop_column('events', 'role')
    # ### end Alembic commands ###
